### ISSUE TITLE
Steering Wheel Mount iPad (Second Screen) 

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/tesla-mobile-office#4]
As a person who works in their car because they need peace and quiet to focus,
I need a way of mounting my second screen [iPad](https://github.com/dwyl/studio/issues/12#issuecomment-673840821) to the steering wheel 
So that I am not staring off to the right (centre console) and creating a crick in my neck ...

# Todo

+ [ ] Measure the dimensions of the steering wheel 
+ [ ] Measure / google dimensions of iPads (make compatible with several devices)
+ [ ] Create flat-packable design for holder that can be cut on Laser cutter from 10mm Plywood

```
This repo is basically the definition of "first world problems" 🙄 
boy works really hard at well-paying-job for 20 years saves money diligently and buys safe car as reward ...
So if you are sensitive about that kind of thing, ❄️ 
please use the browser back button to navigate back to safety. 🙏 
```

**Comment by nelsonic** [comment]
See: https://github.com/nelsonic/tesla-mobile-office/issues/7#issuecomment-2266653257
