### ISSUE TITLE
`Braga` to `London` by Tesla?

### ISSUE THREAD

**Issue by nelsonic** [nelsonic/tesla-mobile-office#6]
I need to visit London next month and was considering _driving_ instead of Flying. 💡 
Obviously it will take _considerably_ longer in terms of **time**. ⏳ 
But how much will it cost in terms of **cash**? 🤷‍♂️ 

# Todo 📝 

+ [ ] Research the expected total trip costs:
  + [ ] Supercharging
  + [ ] Accommodation (if I can't [sleep in the car](https://youtu.be/S5fn1DfqPfA?t=52) ...) for 1 night 
  + [ ] Tolls
  + [ ] Channel Crossing
  + [ ] Parking fees in London (can't park near our house for free ... 🙄)
+ [ ] Figure out the cost each way and if it's safe to assume we can just double it for the return journey.

**Comment by nelsonic** [comment]
There is no shortage of people making videos about _sleeping_ in a **`Model 3`**: ⛺ 
https://www.youtube.com/results?search_query=sleeping+in+tesla+3
<img width="1114" alt="image" src="https://user-images.githubusercontent.com/194400/187046016-ac5e2f8c-f267-40f6-9a66-44a2c5883500.png">

Would only consider this if there was no other option ... 💭 
think that a good night's sleep might be more valuable than a **`€60`** budget hotel.  🏨

**Comment by iteles** [comment]
## Supercharging
We paid around €0.53-0.54 / kWh in Spain for the superchargers we used this Summer, France is likely to be more.

## Parking in London at our flat
On parking "near our house in London", we have a visitor's parking permit which is 1 day parking at a time so you can park on the estate no problem, I can activate the parking online 👍 
It's about **£1.40 a day** (just under) because I bought 60 x 1 day visitor permits.

**Comment by iteles** [comment]
## Tolls
> Tolls between Valladolid and Ouistreham/Caen totalled  €72.50 (one way) so to Calais it would be a bit more I guess cos you are travelling more roads. Most of the tolls were in France. Only one toll in Spain at €15. 

Caen to Calais is still a fair bit so I would budget an extra €30 conservatively of tolls:

<img width="516" alt="image" src="https://user-images.githubusercontent.com/4185328/187960430-903610e0-87f0-4880-b8dd-81d1fe3f50bf.png">



Plus tolls in Portugal, maybe another €20, **totalling about €125 in tolls each way** (about the same as a flight for one person with no luggage at the moment).
https://goo.gl/maps/9ZXoxN1kM3URNxiW8
<img width="784" alt="image" src="https://user-images.githubusercontent.com/4185328/187960804-01d8aefd-0c7e-47a7-b30d-ff1d369774aa.png">

**Comment by nelsonic** [comment]
Ended up flying and renting a car as it was cheaper when we factor all costs (my time, depreciation on the car, etc.)
Closing
